<?php
/**
 * Created by PhpStorm.
 * User: Abduahad
 * Date: 2018/4/18
 * Time: 14:58
 */

namespace Admin\Controller;


use Common\Controller\AdminbaseController;

class ActivityOrderController extends AdminbaseController
{

    private $status = [
        1=>'未支付',
        2=>'报名成功',
        5=>'已取消'
    ];
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index(){

	
        $where = array();
        if($this->role=='agent'){
            $where['a.agent_id'] = $this->uid;
        }
        if($key = I('keyword')){
            $where['m.parent_name|m.child_name|o.sn|m.phone'] = array('like','%'.$key.'%');
        }
        if (I('status')){
            $where['o.status'] = I('status');
        }
        $count = D('ActivityOrder')
            ->alias('o')
            ->join('left join __ACTIVITY__ a on o.activity_id = a.id')
            ->join('left join __PARENTS__ m on o.uid = m.id')
            ->where($where)
            ->count();
        $page = $this->page($count,12);
        $list = D('ActivityOrder')
            ->alias('o')
            ->join('left join __ACTIVITY__ a on o.activity_id = a.id')
            ->join('left join __ACTIVITY_ATTR__ aa on o.attr_id = aa.id')
            ->join('left join __PARENTS__ m on o.uid = m.id')
            ->where($where)
            ->order('sign_time desc')
            ->limit($page->firstRow.','.$page->listRows)
            ->field('o.*,a.title as act_name,m.parent_name,m.phone as parent_phone,aa.title as attr_title')
            ->select();
        $this->assign('list',$list);
        $this->assign("page", $page->show('Admin'));
        $this->assign('status',$this->status);
        $this->display();
    }

    //拼图订单
    public function spell_index()
    {
        $where = [];
        $activity_spell = M('activity_spell');
        $count = $activity_spell
            ->where($where)
            ->count();
        $page = $this->page($count,12);
		
        $data = $activity_spell
            ->alias('acs')
            ->join('left join __ACTIVITY__ a on acs.act_id = a.id')
            ->join('left join __ACTIVITY_ATTR__ aa on acs.act_id = aa.act_id')
            ->where($where)
            ->field('acs.id,acs.create_time,acs.people_num,acs.current_num,acs.status,a.title as act_name,aa.title as attr_title')
            ->limit($page->firstRow.','.$page->listRows)
            ->order('id')
            ->select();
			
        $activity_order = D('activity_order');
		
        foreach ($data as &$datum) {
            $datum['list'] = $activity_order
                ->alias('o')
                ->join('left join __PARENTS__ m on o.uid = m.id')
                ->where(['spell_id'=>$datum['id']])
                ->order('sign_time desc')
                ->field('o.*,m.parent_name,m.phone as parent_phone')
                ->select();
        }
        //pr($data);die;
        $this->assign('list',$data);
        $this->assign("page", $page->show('Admin'));
        $this->assign('status1',$this->status);
        $this->status = [1=>'进行中' ,2=>'已成团' ,3=>'已取消'];
        $this->assign('status',$this->status);
        $this->display();
    }

    public function view()
    {
        if (I('id')) {
            $list = D('ActivityOrder')
                ->alias('o')
                ->join('left join __ACTIVITY__ a on o.activity_id = a.id')
                ->join('left join __ACTIVITY_ATTR__ aa on o.attr_id = aa.id')
                ->join('left join __PARENTS__ m on o.uid = m.id')
                ->where(['o.id'=>I('id')])
                ->field('o.*,a.title as act_name,m.parent_name,m.phone as parent_phone,aa.title as attr_title')
                ->find();
            $list['list'] = M('act_order_detail')->where(['order_id'=>$list['id']])->select();
        }
        $this->assign('statuss',$this->status);
//        pr($this->status);die;
        $this->assign($list);
        $this->display();
    }
}