<?php
/**
 * Created by PhpStorm.
 * User: Abduahad
 * Date: 2018/4/18
 * Time: 14:58
 */

namespace Admin\Controller;


use Common\Controller\AdminbaseController;

class OnlineClassOrderController extends AdminbaseController
{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->assign('status',array(
            1=>'未支付',
            2=>'购买成功',
        ));
    }

    public function index(){

        $where = array();
        if($key = I('keyword')){
            $where['p.parent_name|p.child_name|o.sn|p.phone|oc.title'] = array('like','%'.$key.'%');
        }
        if (I('status')){
            $where['o.status'] = I('status');
        }
        $count = D('OnlineClassOrder')
            ->alias('o')
            ->join('left join fzm_online_class oc on oc.id = o.oc_id')
            ->join('left join fzm_parents p on p.id = o.parent_id')
            ->where($where)
            ->count();
        $page = $this->page($count,12);
        $list = D('OnlineClassOrder')
            ->alias('o')
            ->join('left join fzm_online_class oc on oc.id = o.oc_id')
            ->join('left join fzm_parents p on p.id = o.parent_id')
            ->where($where)
            ->order('o_time desc')
            ->limit($page->firstRow.','.$page->listRows)
            ->field('o.*, oc.title, p.child_name, p.phone')
            ->select();

        foreach ($list as &$item){
            if ($item['u_type']==1){
                //老师
                $item['user_name'] = M('Teacher')->where(['id'=>$item['tid']])->getField('name');
            }elseif ($item['u_type']==2){
                //商户
                $item['user_name'] = M('SmallTable')->where(['id'=>$item['tid']])->getField('s_name');
            }else{
                $item['user_name'] = "平台发布";
            }
        }
        $this->assign('list',$list);
        $this->assign("page", $page->show('Admin'));
        $this->display();
    }

    /**
     * 导出EXCEL
     * sunfan
     *  2017.10.24
     */
    public function oexcel() {

        $where = array();
        if($key = I('keyword')){
            $where['p.parent_name|p.child_name|o.sn|p.phone|oc.title'] = array('like','%'.$key.'%');
        }
        if (I('status')){
            $where['o.status'] = I('status');
        }
        $list = D('OnlineClassOrder')
            ->alias('o')
            ->join('left join fzm_online_class oc on oc.id = o.oc_id')
            ->join('left join fzm_parents p on p.id = o.parent_id')
            ->where($where)
            ->order('o_time desc')
            ->field('o.*, oc.title, p.child_name, p.phone')
            ->select();

        foreach ($list as &$item){
            if ($item['u_type']==1){
                //老师
                $item['user_name'] = M('Teacher')->where(['id'=>$item['tid']])->getField('name');
            }elseif ($item['u_type']==2){
                //商户
                $item['user_name'] = M('SmallTable')->where(['id'=>$item['tid']])->getField('s_name');
            }else{
                $item['user_name'] = "平台发布";
            }
        }
        $str = '
		<table border="1">
		<tr style="background-color:#ccffcc;min-height:30px;">
			<th width="120" align="center">课程标题</th>
			<th align="center">发布人姓名</th>
			<th align="center">发布人身份</th>
			<th align="center">学生姓名</th>
			<th align="center">联系方式</th>
			<th align="center">订单号</th>
			<th align="center">订单总金额（元）</th>
			<th align="center">平台抽成（元）</th>
            <th align="center">优惠券金额（元）</th>
            <th align="center">老师/商户实际到账金额（元）</th>
            <th align="center">下单时间</th>
            <th align="center">状态</th>
		</tr>
		';
        foreach ($list as $key=>&$value) {
            if (($key%2)==0){
                $str .='<tr align="center" style="background-color:#fdffcc;min-height:30px;">';
            }else{
                $str .='<tr align="center" style="min-height:30px;">';
            }
            $status = array(
                1=>'未支付',
                2=>'购买成功',
            );
            $state = $status[$value['status']];

            $type = array(
                1=>'老师',
                2=>'商户',
                3=>'平台',
            );
            $u_type = $type[$value['u_type']];

            $num = 1;
            $str .= '
			<td width="120" rowspan='.$num.'>'.$value['title'].'</td>
			<td rowspan='.$num.'>'.$value['user_name'].'</td>
			<td rowspan='.$num.'>'.$u_type.'</td>
			<td rowspan='.$num.'>'.$value['child_name'].'</td>
			<td rowspan='.$num.'>'.$value['phone'].'</td>
			<td rowspan='.$num.'>'.$value['sn'].'</td>
			<td rowspan='.$num.'>'.$value['total_money'].'</td>
			<td rowspan='.$num.'>'.$value['platform_money'].'</td>
			<td rowspan='.$num.'>'.$value['coupon_money'].'</td>
			<td rowspan='.$num.'>'.$value['money'].'</td>
			<td rowspan='.$num.'>'.$value['o_time'].'</td>
			<td rowspan='.$num.'>'.$state.'</td>
			</tr>';
        }
        $str .="</table>";
        header('Content-Length: '.strlen($str));
        header("Content-type:application/vnd.ms-excel;charset=UTF-8");
        header("Content-Disposition:filename=线上课堂订单表".date('Y-m-d H:i:s').".xls");
        echo $str;
    }
}