<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/7/13 0013
 * Time: 下午 02:50
 */

namespace Managed\Controller;
require('./application/Common/common/JPushSF.php');

class CircleController extends ManagedBaseController
{
    private $uid;

    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->uid = $_SESSION['small_id']?$_SESSION['small_id']:0;
    }

    private function getList($opt=1){
        $db = M('Circle');
        $where = array(
            'option'=>$opt,    //默认亲子时光--1.亲子时光 2.青春日记
            'uid'=>$this->uid,
            'u_type'=>3
        );

        $count = $db
            ->alias('c')
            ->where($where)
            ->count();
        $page = $this->page($count, 15);

        $list = $db
            ->alias('c')
            ->where($where)
            ->limit($page->firstRow,$page->listRows)
            ->order('c_time DESC')
            ->field('c.id as circle_id, c_time, content, img_list, video_url, zan, c.view_num, c_type, uid, u_type')
            ->select();

        foreach ($list as $k=>$item) {
            //图文
            $img_list = $item['img_list'];
            $list[$k]['img_list']=[];
            if($item['c_type']==2){
                $list[$k]['img_list'] = explode(',', $img_list);
            }

            if ($item['u_type']==1){
                //家长用户
                $user = M('Parents')->where(['id'=>$item['uid']])->find();
                $list[$k]['img'] = $user['p_img'];
                $list[$k]['uname'] = $user['parent_name'];
            }elseif ($item['u_type']==2){
                //老师用户
                $user = M('Teacher')->where(['id'=>$item['uid']])->find();
                $list[$k]['img'] = $user['t_img'];
                $list[$k]['uname'] = $user['name'];
            }elseif ($item['u_type']==3){
                //商户用户
                $user = M('SmallTable')->where(['id'=>$item['uid']])->find();
                $list[$k]['img'] = $user['s_img'];
                $list[$k]['uname'] = $user['s_name'];
            }else{
                //后台用户
                $list[$k]['img'] = "/public/images/img_new.png";
                $list[$k]['uname'] = "平台";
            }
        }
        $this->assign('page',$page->show('Admin'));
        $this->assign('list',$list);
    }

    /* 亲子时光 */
    public function index(){
        $this->getList(1);
        $this->display();
    }

    /* 青春时光 */
    public function school(){
        $this->getList(2);
        $this->display();
    }

    /*
     *  添加亲子
     */
    public function add(){
        if(IS_POST){
            if($this->insert(1)){
                $this->success("添加成功",U('Circle/index'));

                //推送
                //查到所有关注我的人
                $collect = M('Collection')->where(['item_id'=>$this->uid, 'type'=>2])->select();
                //给家长推送
                $push = new \JPushSF(C('JPush.PAPPID'),C('JPush.PAPPSECRET'));
                if (!empty($collect))foreach ($collect as $k=>$item){
                    $alias = 'parent'.$item['parent_id'];
                    $receive = array('alias'=>[$alias]);//别名
                    $result = $push->push($receive,0, '您关注的人又有新的动态了，快去看看吧~');
                }
                exit();
            }
            $this->error("添加失败");
        }
        $this->display();
    }

    /**
     *  亲子时光编辑
     */

    public function edit(){
        if(IS_POST){
            $save = $this->update();
            $id = I('post.id',0);
            if($save){
                $this->success('保存成功',U('Circle/edit',array('id'=>$id)));
                exit();
            }
            $this->error('系统错误');
        }
        $id = I('get.id',0);
        $data = D('Circle')->where(array('id'=>$id))->find();
        $this->assign('data',$data);
        $list = explode(',',$data['img_list']);
        $img_list = array();
        foreach ($list as $k => $img){
            $img_list[$k]['url'] = $img;
            $img_list[$k]['alt'] = $img;
        }
        $this->assign('img_list',$img_list);
        $this->display();
    }

    /*
     *  校园日记编辑
     */
    public function editLog(){
        if(IS_POST){
            $save = $this->update();
            $id = I('post.id',0);
            if($save){
                $this->success('保存成功',U('Circle/editLog',array('id'=>$id)));
                exit();
            }
            $this->error('系统错误');
        }
        $id = I('get.id',0);
        $data = D('Circle')->where(array('id'=>$id))->find();
        $this->assign('data',$data);
        $list = explode(',',$data['img_list']);
        $img_list = array();
        foreach ($list as $k => $img){
            $img_list[$k]['url'] = $img;
            $img_list[$k]['alt'] = $img;
        }
        $this->assign('img_list',$img_list);
        $this->display();
    }

    /*
     *  添加校园
     */
    public function addLog(){
        if(IS_POST){
            if($this->insert(2)){
                $this->success("添加成功",U('Circle/school'));exit();
            }
            $this->error("添加失败");
        }
        $this->display();
    }

    private function insert($opt=1){
        $data = array(
            'c_time'=>date('Y-m-d H:i:s'),
            'u_type'=>3,
            'uid'=>$this->uid,
            'c_type'=>I('post.c_type',1),
            'content'=>I('post.content'),
            'option'=>$opt
        );
        if(I('post.c_type')==3){
            $data['video_cover']="/".I('post.video_cover');
            $data['video_url']="/".I('post.video_url');
        }elseif (I('post.c_type')==2){
            $data['img_list'] = implode(',',I('post.photos_url'));
        }
        return D('Circle')->add($data);
    }


    private function update(){
        $id = I('post.id',0);
        $data = array(
            'c_time'=>date('Y-m-d H:i:s'),
            'c_type'=>I('post.c_type',1),
            'content'=>I('post.content'),
        );
        if(I('post.c_type')==3){
            $data['video_cover']=I('post.video_cover');
            $data['video_url']=I('post.video');
        }elseif (I('post.c_type')==2){
            $data['img_list'] = implode(',',I('post.photos_url'));
        }
        try{
            D('Circle')->where(array('id'=>$id))->save($data);
            return true;
        }catch(\Exception $e){
            return false;
        }
    }

    /*
     *  删除
     */

    public function del(){
        $id = $_REQUEST['id'];
        $data = D('Circle')->where(array('id'=>$id))->find();
        if($data){
            $imgs = explode(',',$data['img_list']);
            foreach ($imgs as $img){
                unlink('.'.$img);
            }
            unlink('.'.$data['video_cover']);
            unlink('.'.$data['video_url']);
            if(D('Circle')->where(array('id'=>$id))->delete()){
                
                echo json_encode(['code'=>1]);exit();
            }
        }
        $this->error('删除失败');
    }

}
