<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/7/18 0018
 * Time: 下午 2:06
 */

namespace Managed\Controller;

use Think\Page;
use Think\Controller;

class OnlineController extends ManagedBaseController
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->assign('status',array(
            1=>'未支付',
            2=>'购买成功',
        ));
    }

    //线上课列表
    public function index(){
        if(I("keyword")){
            $keyword = trim(I("keyword"));
            $where['m.title'] = ['like',"%$keyword%"];
            $this->assign('keyword',$keyword);
        }
        $where['m.status'] = ['neq', 3];
        $where['m.tid'] = $_SESSION['small_id'];
        $where['m.u_type'] = 2;
        $model = M("OnlineClass");
        $count = $model->alias('m')
            ->join("LEFT JOIN fzm_teacher t on t.id = m.tid")
            ->where($where)
            ->count();
        $page = $this->page($count,15);
        $info = $model->alias('m')
            ->join("LEFT JOIN fzm_teacher t on t.id = m.tid")
            ->order('sort desc')
            ->where($where)
            ->limit($page->firstRow,$page->listRows)
            ->field('m.*, t.name')
            ->select();

        $this->assign('page',$page->show('Admin'));
        $this->assign('info',$info);
        $this->display();
    }
    //添加
    public function add(){
        if(IS_POST){
            $data = I('post.');
            if(!$data['sub1']){
                $this->error('请选择一级学科');
            }
            if(!$data['sub2']){
                $this->error('请选择二级学科');
            }
            if(!$data['sub3']){
                $this->error('请选择三级学科');
            }
            if(empty($data['title'])){
                $this->error('请填写标题');
            }
            if ($data['price_type'] == 1) {
                if($data['price'] <= 0 || !preg_match('/^[0-9]+(.[0-9]{1,2})?$/', $data['price'])){
                    $this->error('请输入大于0的并且最多2为小数的价格');
                }
                if($_POST['access_password']==true && !preg_match('/^(\w){4,8}$/',$data['access_password'])){
                    $this->error('只能输入4-8个字母、数字、下划线');
                }
            }
            if(!$data['video_cover'] || !$data['video_url']){
                $this->error('您好，请上传视频和封面图！');
            }
            $online_class = D("OnlineClass");
            $config = M('Config')->find();
            $info = $online_class->add([
                'title'           =>      $data['title'],
                'u_type'          =>      2,
                'img_url'         =>      $data['video_cover'],
                'video_url'       =>      $data['video_url'],
                'oc_time'         =>      date('Y-m-d H:i:s'),
                'price'           =>      $data['price'],
                'content'         =>      $_POST['content'],
                't_sub1'          =>      $data['sub1'],
                't_sub2'          =>      $data['sub2'],
                't_sub3'          =>      $data['sub3'],
                'price_type'      =>      $data['price_type'],
                'access_password' =>      $data['access_password'],
                'age_min'         =>      $data['age_min'],
                'age_max'         =>      $data['age_max'],
                'hot'             =>      $data['hot'],
                'tid'             =>      $_SESSION['small_id']
            ]);
            if($info){
                $this->success('添加成功');
            }else{
                $this->error('网络错误');
            }
        }else{
            $subject = D("subject");
            $sub1 = $subject->where(['parentid'=>0])->select();
            $ages = M('ages')->field('id,min,max')->order('id')->select();
            foreach ($ages as &$item) {
                if ($item['max'] == 0) {
                    $item['title'] = $item['min'].'岁以上';
                } else {
                    $item['title'] = $item['min'].'-'.$item['max'].'岁';
                }
                unset($item['min']);
                unset($item['max']);
            }
            $this->assign('sub1',$sub1);
            $this->assign('ages',$ages);
            $this->display();
        }
    }
    //二级学科接口
    public function subject(){
        $id = I("post.id");
        $subject = D("subject");
        $sub1 = $subject->where(['parentid'=>$id])->order('sort asc')->select();
        echo json_encode($sub1);
        exit();
    }


    public function order(){

        $where = array();
        $where['o.tid'] = $_SESSION['small_id'];
        $where['o.u_type'] = 2;
        if($key = I('keyword')){
            $where['p.parent_name|p.child_name|o.sn|p.phone|oc.title'] = array('like','%'.$key.'%');
        }
        if (I('status')){
            $where['o.status'] = I('status');
        }
        $count = D('OnlineClassOrder')
            ->alias('o')
            ->join('left join fzm_online_class oc on oc.id = o.oc_id')
            ->join('left join fzm_parents p on p.id = o.parent_id')
            ->where($where)
            ->count();
        $page = $this->page($count,12);
        $list = D('OnlineClassOrder')
            ->alias('o')
            ->join('left join fzm_online_class oc on oc.id = o.oc_id')
            ->join('left join fzm_parents p on p.id = o.parent_id')
            ->where($where)
            ->order('o_time desc')
            ->limit($page->firstRow.','.$page->listRows)
            ->field('o.*, oc.title, p.child_name, p.phone')
            ->select();

        foreach ($list as &$item){
            if ($item['u_type']==1){
                //老师
                $item['user_name'] = M('Teacher')->where(['id'=>$item['tid']])->getField('name');
            }elseif ($item['u_type']==2){
                //商户
                $item['user_name'] = M('SmallTable')->where(['id'=>$item['tid']])->getField('s_name');
            }else{
                $item['user_name'] = "平台发布";
            }
        }
        $this->assign('list',$list);
        $this->assign("page", $page->show('Admin'));
        $this->display();
    }
    public function edit(){
        $online_class = D("OnlineClass");

        if(IS_POST){
            $id = I("post.id",0);
            if(!$_POST['sub1']){
                $this->error('请选择一级学科');
            }
            if(!$_POST['sub2']){
                $this->error('请选择二级学科');
            }
            if(!$_POST['sub3']){
                $this->error('请选择三级学科');
            }
            if(empty($_POST['title'])){
                $this->error('请填写标题');
            }
            if ($_POST['price_type'] == 1) {
                if($_POST['price'] <= 0 || !preg_match('/^[0-9]+(.[0-9]{1,2})?$/', $_POST['price'])){
                    $this->error('请输入大于0的并且最多2为小数的价格');
                }
                if($_POST['access_password']==true && !preg_match('/^(\w){4,8}$/',$_POST['access_password'])){
                    $this->error('只能输入4-8个字母、数字、下划线');
                }
            }
            if(!$_POST['video_cover'] || !$_POST['video']){
                $this->error('您好，请上传视频和封面图！');
            }
            $config = M('Config')->find();
            $online_class->where(['id'=>$id])->save([
                'title'           =>      $_POST['title'],
                'img_url'         =>      $_POST['video_cover'],
                'video_url'       =>      $_POST['video'],
                'price'           =>      $_POST['price_type']==1?$_POST['price']:0,
                'content'         =>      $_POST['content'],
                't_sub1'          =>      $_POST['sub1'],
                't_sub2'          =>      $_POST['sub2'],
                't_sub3'          =>      $_POST['sub3'],
                'price_type'      =>      $_POST['price_type'],
                'access_password' =>      $_POST['access_password'],
                'age_min'         =>      $_POST['age_min'],
                'age_max'         =>      $_POST['age_max'],
            ]);
            $this->success('保存成功');
        }else{
            $id = I("get.id",0,'intval');
            $info = $online_class->where(['id'=>$id])->find();
            $subject = D("subject");

            $sub1 = $subject->where(['parentid'=>0])->order('sort asc')->select();
            $sub2_id = $subject->where(['s_name'=>$info['t_sub1']])->find();
            $sub3_id = $subject->where(['s_name'=>$info['t_sub2']])->find();
            $sub2 = $subject->where(['parentid'=>$sub2_id['id']])->order('sort asc')->select();
            $sub3 = $subject->where(['parentid'=>$sub3_id['id']])->order('sort asc')->select();
            $ages = M('ages')->field('id,min,max')->order('id')->select();
            foreach ($ages as &$item) {
                if ($item['max'] == 0) {
                    $item['title'] = $item['min'].'岁以上';
                } else {
                    $item['title'] = $item['min'].'-'.$item['max'].'岁';
                }
                unset($item['min']);
                unset($item['max']);
            }
            $this->assign('sub1',$sub1);
            $this->assign('sub2',$sub2);
            $this->assign('sub3',$sub3);
            $this->assign('ages',$ages);
            $this->assign('info',$info);
            $this->display();
        }
    }
    //禁用
    public function ban(){
        $id = I('id');
        $status = I('status');
        if($id){
            if($status){
                $info = M('OnlineClass')->where(array('id'=>$id))->save(array('status'=>$status));
                if($info){
                    $arr['code'] = 1;
                }else{
                    $arr['msg'] = '修改失败';
                }
            }else{
                $arr['code'] = '网络错误';
            }

        }else{
            $arr['code'] = '数据传输错误';
        }
        echo json_encode($arr);
        exit();
    }
    //删除
    public function delete(){
        $id = I('post.id',0,'intval');
        $info = M('OnlineClass')->where(array('id'=>$id))->save(array('status'=>3));
        if($info){
            $arr['code'] = 1;
        }else{
            $arr['msg'] = '删除失败';
        }
        echo json_encode($arr);
        exit();
    }

    //查看评论
    public function comment()
    {
        $id = I('id',0,'intval');
        $evaluate = D("OnlineEvaluate");
        $where['o.c_id'] = $id;
        $count = $evaluate->alias('o')
            ->join("LEFT JOIN fzm_parents p on o.uid = p.id")
            ->where($where)
            ->count();
        $page = $this->page($count, 15);
        $list = $evaluate->alias('o')
            ->join("LEFT JOIN fzm_parents p on o.uid = p.id")
            ->limit($page->firstRow . ',' . $page->listRows)
            ->order("o.create_time desc")
            ->where($where)
            ->field('o.id, o.create_time,o.content,p.parent_name,p.p_img')
            ->select();
        $this->assign("page", $page->show('Admin'));
        $this->assign('info', $list);
        $this->display();
    }

}